[phases.setup]
nixPkgs = [
  "python311",
  "chromium",
  "chromedriver",
  "gcc",
  "zlib",
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install undetected-chromedriver"
]

[start]
cmd = "python run_bot.py"
